name: Run Python script daily at 17:00 and allow manual triggers

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      run: python main.py
